### ISSUE TITLE
Hyperlinking URL issue

### ISSUE THREAD

**Issue by Travis-S** [wrightaprilm/wrightaprilm.github.io#5]
It looks like there is an issue with the hyperlinks on the website. In particular, it appears there is a duplication of the website name in each URL. As can be seen in the first screenshot, this also affects the linking to the CSS. In the second, I clicked on the title of the post in the first screenshot, and got the 404 page.

However, I downloaded the site's `.zip` file and browsed the HTML on my local machine, and the CSS showed up correctly, and all the links worked. So it could be something about how GitHub pages work. Perhaps the use of the absolute URLs is messing with GitHub pages.

![screen shot 2015-05-07 at 2 06 23 pm](https://cloud.githubusercontent.com/assets/6274641/7524899/56b93108-f4c2-11e4-8ef2-f9ca169781c4.png)
![screen shot 2015-05-07 at 2 06 27 pm](https://cloud.githubusercontent.com/assets/6274641/7524902/59893180-f4c2-11e4-85bf-c25bb4e8241f.png)

**Comment by wrightaprilm** [comment]
Thanks, Travis, and sorry I'm so late in getting on this. Dissertation, baby, etc - finally remembered when someone tweeted at me this morning. It looks like I somehow got some absolute paths in with the html, which normally takes relative paths, so when pelican went to assemble URLs, they each got a double dose of 'wrightaprilm.github.io'. Not a huge deal for the local, but a problem for git deployment.

Thanks for filing this!
